# The item to act in place of shears.
SHEARS: 359

# The item to act in place of paper.
PAPER: 339

# Dye Chart
# 0 - Ink Sac
# 1 - Rose Red
# 2 - Cactus Green
# 3 - Cocoa Beans
# 4 - Lapis Lazuli
# 5 - Purple Dye
# 6 - Cyan Dye
# 7 - Light Gray Dye
# 8 - Gray Dye
# 9 - Pink Dye
# 10 - Lime Dye
# 11 - Dandelion Yellow
# 12 - Light Blue Dye
# 13 - Magenta Dye
# 14 - Orange Dye
# 15 - Bone Meal

# The dye number for the rose dye.
ROSE: 1

# The dye number for the lime dye.
LIME: 10